version: '3'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tesseract
  openars:
    build: OpenARS/.
    expose:
      - "8443"
    ports:
      - "8443:8443"
    restart: unless-stopped
    environment:
      - SPRING_RABBITMQ_HOST=broker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/tesseract
  broker:
    image: rabbitmq
  commentservice:
    build: CommentService/.
    environment:
      - SPRING_RABBITMQ_HOST=broker
      - SPRING_MAIL_PASSWORD=buxkrgblerpbkfim
    
  
